// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQ7BaetkGiZ0Ebh6qPpdBbAvpgSYxg3k',
    appId: '1:352349753213:android:46923b9dc5fab7be130614',
    messagingSenderId: '352349753213',
    projectId: 'nephrologyhemo',
    storageBucket: 'nephrologyhemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2gXxueuKVjG0cy_8jq6KDKF80halyoE',
    appId: '1:352349753213:ios:4238b8eba64efbe1130614',
    messagingSenderId: '352349753213',
    projectId: 'nephrologyhemo',
    storageBucket: 'nephrologyhemo.appspot.com',
    iosBundleId: 'com.example.nephrohemo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6tIj7ERHVimui-x9u--_vUe5VaZW8tdQ',
    appId: '1:352349753213:web:0ae8d26bbaef9e5f130614',
    messagingSenderId: '352349753213',
    projectId: 'nephrologyhemo',
    authDomain: 'nephrologyhemo.firebaseapp.com',
    storageBucket: 'nephrologyhemo.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2gXxueuKVjG0cy_8jq6KDKF80halyoE',
    appId: '1:352349753213:ios:4238b8eba64efbe1130614',
    messagingSenderId: '352349753213',
    projectId: 'nephrologyhemo',
    storageBucket: 'nephrologyhemo.appspot.com',
    iosBundleId: 'com.example.nephrohemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6tIj7ERHVimui-x9u--_vUe5VaZW8tdQ',
    appId: '1:352349753213:web:a68eaa66ca411f7a130614',
    messagingSenderId: '352349753213',
    projectId: 'nephrologyhemo',
    authDomain: 'nephrologyhemo.firebaseapp.com',
    storageBucket: 'nephrologyhemo.appspot.com',
  );

}